[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  # Disable secret scanning for Firebase client keys (they're meant to be public)
  NETLIFY_SKIP_SECRET_SCANNING = "true"

# Optional: Add redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200